# Generated by Django 4.1.7 on 2023-03-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_alter_recipeingredient_quantity'),
        ('accounts', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shopping_list',
            field=models.ManyToManyField(related_name='shopping_list', to='recipes.recipe'),
        ),
    ]
