# Generated by Django 4.1.7 on 2023-03-13 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_remove_recipe_favourites_alter_recipe_diet_and_more'),
        ('accounts', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favourite_list',
            field=models.ManyToManyField(blank=True, related_name='favourites_user', to='recipes.recipe'),
        ),
        migrations.CreateModel(
            name='InteractedWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_interaction', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='history_list',
            field=models.ManyToManyField(blank=True, related_name='history_user', through='accounts.InteractedWith', to='recipes.recipe'),
        ),
    ]
