# Generated by Django 4.1.7 on 2023-03-14 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_favourite_list_interactedwith_and_more'),
        ('accounts', '0004_customuser_shopping_list'),
    ]

    operations = [
    ]
