# Generated by Django 4.1.7 on 2023-03-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20230314_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactedwith',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interactedwith',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
