# Generated by Django 4.1.7 on 2023-03-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_interactedwith_liked_interactedwith_rated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactedwith',
            name='rated',
        ),
        migrations.AddField(
            model_name='interactedwith',
            name='rating',
            field=models.IntegerField(default=-1),
        ),
    ]
