# Generated by Django 4.1.7 on 2023-03-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('accounts', '0005_merge_20230314_2341'),
        ('accounts', '0007_remove_interactedwith_rated_interactedwith_rating'),
    ]

    operations = [
    ]
