# Generated by Django 4.1.7 on 2023-03-05 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cuisine', models.CharField(choices=[('NONE', 'None'), ('CN', 'Chinese'), ('CR', 'Creole'), ('FR', 'French'), ('GR', 'Indian'), ('IT', 'Italian'), ('JP', 'Japanese'), ('KO', 'Korean'), ('ME', 'Middle East'), ('WE', 'Western')], default='NONE', max_length=4)),
                ('diet', models.CharField(choices=[('NONE', 'None'), ('VEGAN', 'Vegan'), ('VEG', 'Vegeterian'), ('GLUTENF', 'Gluten free'), ('LCARB', 'Low carb'), ('KT', 'Keto'), ('LF', 'Low fat')], default='NONE', max_length=7)),
                ('cooking_time', models.PositiveIntegerField(default=0)),
                ('serving_size', models.PositiveIntegerField(default=1)),
                ('directions', models.TextField()),
                ('num_fav', models.PositiveIntegerField(default=0)),
                ('num_likes', models.PositiveIntegerField(default=0)),
                ('ave_rating', models.PositiveIntegerField(default=0)),
                ('base_recipe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseRecipe', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField(default=0)),
                ('units', models.CharField(choices=[('NONE', 'None'), ('CUPS', 'Cups'), ('TSP', 'Teaspoon'), ('TBSP', 'Tablespoon')], default='NONE', max_length=4)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
