# Generated by Django 4.1.7 on 2023-04-06 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_cuisine'),
        ('recipes', '0002_alter_recipe_cuisine_alter_recipe_picture'),
    ]

    operations = [
    ]
