# Generated by Django 4.1.7 on 2023-03-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='list',
            field=models.TextField(default=''),
        ),
    ]
