# Generated by Django 4.1.7 on 2023-03-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='list',
            new_name='ingredients_list',
        ),
    ]
