# Generated by Django 4.1.7 on 2023-03-10 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favourites',
            field=models.ManyToManyField(related_name='favouriteRecipe', to=settings.AUTH_USER_MODEL),
        ),
    ]
