# Generated by Django 4.1.7 on 2023-03-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_direction_listdirections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
