# Generated by Django 4.1.7 on 2023-03-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_direction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='directions',
        ),
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.ManyToManyField(to='recipes.direction'),
        ),
    ]
