# Generated by Django 4.1.7 on 2023-03-10 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_recipe_directions_recipe_directions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListDirections',
        ),
    ]
