# Generated by Django 4.1.7 on 2023-03-10 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_favourites'),
        ('recipes', '0011_delete_listdirections'),
    ]

    operations = [
    ]
