# Generated by Django 4.1.7 on 2023-03-11 23:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_merge_20230310_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favourites',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diet',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NONE', 'None'), ('VEGAN', 'Vegan'), ('VEG', 'Vegeterian'), ('GLUTENF', 'Gluten free'), ('LCARB', 'Low carb'), ('KT', 'Keto'), ('LF', 'Low fat')], default='NONE', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='units',
            field=models.CharField(choices=[('NONE', 'None'), ('CUPS', 'cup(s)'), ('TSP', 'teaspoon(s)'), ('TBSP', 'tablespoon(s)'), ('POUND', 'pound(s)')], default='NONE', max_length=5),
        ),
    ]
