# Generated by Django 4.1.7 on 2023-03-11 14:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_diet_alter_recipeingredient_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='diet',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NONE', 'None'), ('VEGAN', 'Vegan'), ('VEG', 'Vegeterian'), ('GLUTENF', 'Gluten free'), ('LCARB', 'Low carb'), ('KT', 'Keto'), ('LF', 'Low fat')], default='NONE', max_length=100),
        ),
    ]
