# Generated by Django 4.1.7 on 2023-03-12 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_merge_20230310_1805'),
        ('recipes', '0013_alter_recipe_diet'),
    ]

    operations = [
    ]
