# Generated by Django 4.1.7 on 2023-03-14 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_remove_recipe_favourites_alter_recipe_diet_and_more'),
        ('recipes', '0015_remove_recipe_favourites'),
    ]

    operations = [
    ]
