# Generated by Django 4.1.7 on 2023-03-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_shoppinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='recipe_list',
            field=models.TextField(default=''),
        ),
    ]
