# Generated by Django 4.1.7 on 2023-03-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_merge_20230314_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
