# Generated by Django 4.1.7 on 2023-03-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_recipeingredient_quantity'),
        ('recipes', '0017_alter_recipeingredient_quantity'),
    ]

    operations = [
    ]
