# Generated by Django 4.1.7 on 2023-03-14 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_alter_recipeingredient_quantity'),
        ('recipes', '0018_merge_20230314_1817'),
    ]

    operations = [
    ]
