# Generated by Django 4.1.7 on 2023-03-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_merge_20230314_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='recipe_list',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='recipes',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='list_ingredients',
            field=models.ManyToManyField(to='recipes.recipeingredient'),
        ),
    ]
