# Generated by Django 4.1.7 on 2023-03-14 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_merge_20230314_2150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
