# Generated by Django 4.1.7 on 2023-03-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_delete_shoppinglist'),
        ('recipes', '0020_remove_shoppinglist_name_and_more'),
    ]

    operations = [
    ]
